///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package admin_perm_repo

import (
	"fmt"
	"time"

	"starfission_go_api/global"
	"starfission_go_api/internal/model"
	"starfission_go_api/pkg/timef"

	"github.com/pkg/errors"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

func Connection() *gorm.DB {
	db := global.DBEngine
	db.Config.NamingStrategy = schema.NamingStrategy{
		TablePrefix:   "pre_", // 表名前缀
		SingularTable: true,   // 使用单数表名
	}
	return db
}

func NewModel() *AdminPerm {
	return new(AdminPerm)
}

type adminPermRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	whereRaw []struct {
		query  string
		values []interface{}
	}
	limit  int
	offset int
}

func NewQueryBuilder() *adminPermRepoQueryBuilder {
	return new(adminPermRepoQueryBuilder)
}

func (qb *adminPermRepoQueryBuilder) buildQuery() *gorm.DB {
	ret := Connection()
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, where2 := range qb.whereRaw {
		ret = ret.Where(where2.query, where2.values...)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (t *AdminPerm) Create() (id int64, err error) {
	t.CreatedAt = timef.Now()
	db := Connection()
	if err = db.Model(t).Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Auid, nil
}

func (t *AdminPerm) Save() (err error) {
	t.UpdatedAt = timef.Now()

	db := Connection()
	if err = db.Model(t).Save(t).Error; err != nil {
		return errors.Wrap(err, "update err")
	}
	return nil
}

func (qb *adminPermRepoQueryBuilder) Updates(m map[string]interface{}) (err error) {

	db := Connection()
	db = db.Model(&AdminPerm{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

// 自减
func (qb *adminPermRepoQueryBuilder) Increment(column string, value int64) (err error) {

	db := Connection()
	db = db.Model(&AdminPerm{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Update(column, gorm.Expr(column+" + ?", value)).Error; err != nil {
		return errors.Wrap(err, "increment err")
	}
	return nil
}

// 自增
func (qb *adminPermRepoQueryBuilder) Decrement(column string, value int64) (err error) {

	db := Connection()
	db = db.Model(&AdminPerm{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Update(column, gorm.Expr(column+" - ?", value)).Error; err != nil {
		return errors.Wrap(err, "decrement err")
	}
	return nil
}

func (qb *adminPermRepoQueryBuilder) Delete() (err error) {

	db := Connection()
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&AdminPerm{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *adminPermRepoQueryBuilder) Count() (int64, error) {
	var c int64
	res := qb.buildQuery().Model(&AdminPerm{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *adminPermRepoQueryBuilder) First() (*AdminPerm, error) {
	ret := &AdminPerm{}
	res := qb.buildQuery().First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *adminPermRepoQueryBuilder) Get() ([]*AdminPerm, error) {
	return qb.QueryAll()
}

func (qb *adminPermRepoQueryBuilder) QueryOne() (*AdminPerm, error) {
	qb.limit = 1
	ret, err := qb.QueryAll()
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *adminPermRepoQueryBuilder) QueryAll() ([]*AdminPerm, error) {
	var ret []*AdminPerm
	err := qb.buildQuery().Find(&ret).Error
	return ret, err
}

func (qb *adminPermRepoQueryBuilder) Limit(limit int) *adminPermRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *adminPermRepoQueryBuilder) Offset(offset int) *adminPermRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereRaw(query string, values ...interface{}) *adminPermRepoQueryBuilder {
	vals := make([]interface{}, len(values))
	for i, v := range values {
		vals[i] = v
	}
	qb.whereRaw = append(qb.whereRaw, struct {
		query  string
		values []interface{}
	}{
		query,
		vals,
	})
	return qb
}

// ----------

func (qb *adminPermRepoQueryBuilder) WhereAuid(p model.Predicate, value int64) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "auid", p),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereAuidIn(value []int64) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "auid", "IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereAuidNotIn(value []int64) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "auid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) OrderByAuid(asc bool) *adminPermRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`auid` "+order)
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereModkeyword(p model.Predicate, value string) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "modkeyword", p),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereModkeywordIn(value []string) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "modkeyword", "IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereModkeywordNotIn(value []string) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "modkeyword", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) OrderByModkeyword(asc bool) *adminPermRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`modkeyword` "+order)
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereUpdatedAt(p model.Predicate, value time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) OrderByUpdatedAt(asc bool) *adminPermRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`updated_at` "+order)
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereCreatedAt(p model.Predicate, value time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) OrderByCreatedAt(asc bool) *adminPermRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`created_at` "+order)
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereDeletedAt(p model.Predicate, value time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", p),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereDeletedAtIn(value []time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) WhereDeletedAtNotIn(value []time.Time) *adminPermRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminPermRepoQueryBuilder) OrderByDeletedAt(asc bool) *adminPermRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`deleted_at` "+order)
	return qb
}
