FROM alpine:latest
ENV TZ Asia/Shanghai
RUN apk --update add libstdc++ curl ca-certificates bash curl gcompat tzdata && \
      cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
        echo ${TZ} > /etc/timezone && \
            rm -rf  /tmp/* /var/cache/apk/*

