///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package app_user_repo

import (
	"fmt"
	"time"

	"starfission_go_api/global"
	"starfission_go_api/internal/model"
	"starfission_go_api/pkg/timef"

	"github.com/pkg/errors"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

func Connection() *gorm.DB {
	db := global.DBEngine
	db.Config.NamingStrategy = schema.NamingStrategy{
		TablePrefix:   "pre_", // 表名前缀
		SingularTable: true,   // 使用单数表名
	}
	return db
}

func NewModel() *AppUser {
	return new(AppUser)
}

type appUserRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	whereRaw []struct {
		query  string
		values []interface{}
	}
	limit  int
	offset int
}

func NewQueryBuilder() *appUserRepoQueryBuilder {
	return new(appUserRepoQueryBuilder)
}

func (qb *appUserRepoQueryBuilder) buildQuery() *gorm.DB {
	ret := Connection()
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, where2 := range qb.whereRaw {
		ret = ret.Where(where2.query, where2.values...)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (t *AppUser) Create() (id int64, err error) {
	t.CreatedAt = timef.Now()
	db := Connection()
	if err = db.Model(t).Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.AppUid, nil
}

func (t *AppUser) Save() (err error) {
	t.UpdatedAt = timef.Now()

	db := Connection()
	if err = db.Model(t).Save(t).Error; err != nil {
		return errors.Wrap(err, "update err")
	}
	return nil
}

func (qb *appUserRepoQueryBuilder) Updates(m map[string]interface{}) (err error) {

	db := Connection()
	db = db.Model(&AppUser{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

// 自减
func (qb *appUserRepoQueryBuilder) Increment(column string, value int64) (err error) {

	db := Connection()
	db = db.Model(&AppUser{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Update(column, gorm.Expr(column+" + ?", value)).Error; err != nil {
		return errors.Wrap(err, "increment err")
	}
	return nil
}

// 自增
func (qb *appUserRepoQueryBuilder) Decrement(column string, value int64) (err error) {

	db := Connection()
	db = db.Model(&AppUser{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Update(column, gorm.Expr(column+" - ?", value)).Error; err != nil {
		return errors.Wrap(err, "decrement err")
	}
	return nil
}

func (qb *appUserRepoQueryBuilder) Delete() (err error) {

	db := Connection()
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&AppUser{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *appUserRepoQueryBuilder) Count() (int64, error) {
	var c int64
	res := qb.buildQuery().Model(&AppUser{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *appUserRepoQueryBuilder) First() (*AppUser, error) {
	ret := &AppUser{}
	res := qb.buildQuery().First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *appUserRepoQueryBuilder) Get() ([]*AppUser, error) {
	return qb.QueryAll()
}

func (qb *appUserRepoQueryBuilder) QueryOne() (*AppUser, error) {
	qb.limit = 1
	ret, err := qb.QueryAll()
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *appUserRepoQueryBuilder) QueryAll() ([]*AppUser, error) {
	var ret []*AppUser
	err := qb.buildQuery().Find(&ret).Error
	return ret, err
}

func (qb *appUserRepoQueryBuilder) Limit(limit int) *appUserRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *appUserRepoQueryBuilder) Offset(offset int) *appUserRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereRaw(query string, values ...interface{}) *appUserRepoQueryBuilder {
	vals := make([]interface{}, len(values))
	for i, v := range values {
		vals[i] = v
	}
	qb.whereRaw = append(qb.whereRaw, struct {
		query  string
		values []interface{}
	}{
		query,
		vals,
	})
	return qb
}

// ----------

func (qb *appUserRepoQueryBuilder) WhereAppUid(p model.Predicate, value int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "app_uid", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereAppUidIn(value []int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "app_uid", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereAppUidNotIn(value []int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "app_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByAppUid(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`app_uid` "+order)
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereOpenId(p model.Predicate, value string) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "open_id", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereOpenIdIn(value []string) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "open_id", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereOpenIdNotIn(value []string) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "open_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByOpenId(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`open_id` "+order)
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereUid(p model.Predicate, value int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "uid", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereUidIn(value []int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "uid", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereUidNotIn(value []int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByUid(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`uid` "+order)
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereAppId(p model.Predicate, value int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "app_id", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereAppIdIn(value []int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "app_id", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereAppIdNotIn(value []int64) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "app_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByAppId(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`app_id` "+order)
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereIsDeleted(p model.Predicate, value int32) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereIsDeletedIn(value []int32) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereIsDeletedNotIn(value []int32) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByIsDeleted(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`is_deleted` "+order)
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereCreatedAt(p model.Predicate, value time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByCreatedAt(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`created_at` "+order)
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereUpdatedAt(p model.Predicate, value time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByUpdatedAt(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`updated_at` "+order)
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereDeletedAt(p model.Predicate, value time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", p),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereDeletedAtIn(value []time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) WhereDeletedAtNotIn(value []time.Time) *appUserRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *appUserRepoQueryBuilder) OrderByDeletedAt(asc bool) *appUserRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`deleted_at` "+order)
	return qb
}
