///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package admin_note_repo

import (
	"fmt"
	"time"

	"starfission_go_api/global"
	"starfission_go_api/internal/model"
	"starfission_go_api/pkg/timef"

	"github.com/pkg/errors"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

func Connection() *gorm.DB {
	db := global.DBEngine
	db.Config.NamingStrategy = schema.NamingStrategy{
		TablePrefix:   "pre_", // 表名前缀
		SingularTable: true,   // 使用单数表名
	}
	return db
}

func NewModel() *AdminNote {
	return new(AdminNote)
}

type adminNoteRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	whereRaw []struct {
		query  string
		values []interface{}
	}
	limit  int
	offset int
}

func NewQueryBuilder() *adminNoteRepoQueryBuilder {
	return new(adminNoteRepoQueryBuilder)
}

func (qb *adminNoteRepoQueryBuilder) buildQuery() *gorm.DB {
	ret := Connection()
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, where2 := range qb.whereRaw {
		ret = ret.Where(where2.query, where2.values...)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (t *AdminNote) Create() (id int64, err error) {
	t.CreatedAt = timef.Now()
	db := Connection()
	if err = db.Model(t).Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

func (t *AdminNote) Save() (err error) {
	t.UpdatedAt = timef.Now()

	db := Connection()
	if err = db.Model(t).Save(t).Error; err != nil {
		return errors.Wrap(err, "update err")
	}
	return nil
}

func (qb *adminNoteRepoQueryBuilder) Updates(m map[string]interface{}) (err error) {

	db := Connection()
	db = db.Model(&AdminNote{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

// 自减
func (qb *adminNoteRepoQueryBuilder) Increment(column string, value int64) (err error) {

	db := Connection()
	db = db.Model(&AdminNote{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Update(column, gorm.Expr(column+" + ?", value)).Error; err != nil {
		return errors.Wrap(err, "increment err")
	}
	return nil
}

// 自增
func (qb *adminNoteRepoQueryBuilder) Decrement(column string, value int64) (err error) {

	db := Connection()
	db = db.Model(&AdminNote{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Update(column, gorm.Expr(column+" - ?", value)).Error; err != nil {
		return errors.Wrap(err, "decrement err")
	}
	return nil
}

func (qb *adminNoteRepoQueryBuilder) Delete() (err error) {

	db := Connection()
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&AdminNote{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *adminNoteRepoQueryBuilder) Count() (int64, error) {
	var c int64
	res := qb.buildQuery().Model(&AdminNote{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *adminNoteRepoQueryBuilder) First() (*AdminNote, error) {
	ret := &AdminNote{}
	res := qb.buildQuery().First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *adminNoteRepoQueryBuilder) Get() ([]*AdminNote, error) {
	return qb.QueryAll()
}

func (qb *adminNoteRepoQueryBuilder) QueryOne() (*AdminNote, error) {
	qb.limit = 1
	ret, err := qb.QueryAll()
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *adminNoteRepoQueryBuilder) QueryAll() ([]*AdminNote, error) {
	var ret []*AdminNote
	err := qb.buildQuery().Find(&ret).Error
	return ret, err
}

func (qb *adminNoteRepoQueryBuilder) Limit(limit int) *adminNoteRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *adminNoteRepoQueryBuilder) Offset(offset int) *adminNoteRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereRaw(query string, values ...interface{}) *adminNoteRepoQueryBuilder {
	vals := make([]interface{}, len(values))
	for i, v := range values {
		vals[i] = v
	}
	qb.whereRaw = append(qb.whereRaw, struct {
		query  string
		values []interface{}
	}{
		query,
		vals,
	})
	return qb
}

// ----------

func (qb *adminNoteRepoQueryBuilder) WhereId(p model.Predicate, value int64) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereIdIn(value []int64) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereIdNotIn(value []int64) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) OrderById(asc bool) *adminNoteRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`id` "+order)
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereAuid(p model.Predicate, value int64) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "auid", p),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereAuidIn(value []int64) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "auid", "IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereAuidNotIn(value []int64) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "auid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) OrderByAuid(asc bool) *adminNoteRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`auid` "+order)
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereNotetext(p model.Predicate, value string) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "notetext", p),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereNotetextIn(value []string) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "notetext", "IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereNotetextNotIn(value []string) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "notetext", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) OrderByNotetext(asc bool) *adminNoteRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`notetext` "+order)
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereUpdatedAt(p model.Predicate, value time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) OrderByUpdatedAt(asc bool) *adminNoteRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`updated_at` "+order)
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereCreatedAt(p model.Predicate, value time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) OrderByCreatedAt(asc bool) *adminNoteRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`created_at` "+order)
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereDeletedAt(p model.Predicate, value time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", p),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereDeletedAtIn(value []time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) WhereDeletedAtNotIn(value []time.Time) *adminNoteRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *adminNoteRepoQueryBuilder) OrderByDeletedAt(asc bool) *adminNoteRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "`deleted_at` "+order)
	return qb
}
